language: python
python:
  - "3.6"
notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - TO_TEST=CODE
    - TO_TEST=NOTEBOOKS
    - TO_TEST=STYLE

install:
  - pip install -e .
  - pip install pytest-cov codecov mypy flake8 nose
  - if [ "$TO_TEST" = "NOTEBOOKS" ]; then pip install notebook nbconvert; fi

script:
  - if [ "$TO_TEST" = "CODE" ]; then mypy -p cornerstone_widget --ignore-missing-imports; fi
  - if [ "$TO_TEST" = "CODE" ]; then pytest --cov=cornerstone_widget; fi
  - if [ "$TO_TEST" = "CODE" ]; then codecov; fi
  - if [ "$TO_TEST" = "STYLE" ]; then flake8 --ignore E501,F401; fi
  - if [ "$TO_TEST" = "NOTEBOOKS" ]; then source build_tools/travis_notebooks.sh; fi

deploy:
  provider: pypi
  user: "cornerstonewidget"
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    repo: chestrays/cornerstone_widget
  password:
    secure: "El7nAfCzZttTjmvfDWxU+YlT/pLgnxHMvCIAMP0NcRbFJoI4nyPCSISK9u+u4A6dyVlH0tOFAOwIPjvsT6UIRN7T5a8xZf2nwnyXwLWUvkv9+AbZ4euwwucuSni9shOYTl9P3jWYPU28AeZdGTwLAG+xFFCwcoi+H1fnIUk5Av5djcx+jiYfKetjuEa+Ljw7tHZQSFeD4ZlW/lnTf10UQlY1lZXdo8ht4m6300GGiDlyXPUlxQVWVUBxiZifkq7n0KQA4dC3KGW7V69KUHbDTVtZrf3KbLv5G47XmJNhPMSNYqB2jY6SjD014ASs2/1cj3nnKTArbzLvZHj6tUaVzcRefmofZVTpQ2UT3GYmghRgqc9sj1E3OFTO2qjWWURsBCobI//bZHglKtZu3HknVRz8fzPAAAzfvgmbX0JJZFDltclPtDmbdkiySFllb7CcIZm09vdzdnVsqjFzna3QOP+9qPn1lZE7bcFeET6ANkpfA96ZpepQshTCZcD34dWFcR9JkrCGuu6UPr0KIQofmte553fwWQV9RPYdLLQt3ng8JBSMda6UhTnGYB41DX7SI4yr1Jg1TI6lL5drTjC36NKCae67tetwbx4vEINAeNfZb3DHXXEq4uBwMQ46t78I1pBavcRLHIPzKmUjoRkeuc1p0P2ctt9WuF/nStvp7bE="
