language: python
python:
  - "3.6"
notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - TO_TEST=CODE
    - TO_TEST=NOTEBOOKS
    - TO_TEST=STYLE

install:
  - pip install -e .
  - pip install pytest-cov codecov mypy flake8 nose
  - if [ "$TO_TEST" = "NOTEBOOKS" ]; then pip install notebook nbconvert; fi

script:
  - if [ "$TO_TEST" = "CODE" ]; then mypy -p cornerstone_widget --ignore-missing-imports; fi
  - if [ "$TO_TEST" = "CODE" ]; then pytest --cov=cornerstone_widget; fi
  - if [ "$TO_TEST" = "CODE" ]; then codecov; fi
  - if [ "$TO_TEST" = "STYLE" ]; then flake8 --ignore E501,F401; fi
  - if [ "$TO_TEST" = "NOTEBOOKS" ]; then source build_tools/travis_notebooks.sh; fi
